#!/usr/bin/env python3
import os

from pathlib import Path

hostsfile = Path("funke-hosts")
iosAdguardFile = Path("ios-adguard.txt")
wwwhostnames_file = Path("www-hostnames")
hostnames_file = Path("hostnames")

hostsfile.unlink(missing_ok=True)
iosAdguardFile.unlink(missing_ok=True)

with hostsfile.open("w+") as hosts, iosAdguardFile.open("w+") as iosAdguard, wwwhostnames_file.open("r") as wwwhostnames, hostnames_file.open("r") as hostnames:

    hosts.write("# This is an autogenerated file by ./generate_hostfile.py with the files \"www-hostnames\" and \"hostnames\"\n\n")

    for line in wwwhostnames.readlines():
        if (line[0] == "\n" or line[0] == "#"):
            continue
        hosts.write("0.0.0.0 " + line)
        iosAdguard.write(line)
        if (line[-1] != "\n"):
            hosts.write("\n")
            iosAdguard.write("\n")
        hosts.write("0.0.0.0 www." + line)
        if (line[-1] != "\n"):
            hosts.write("\n")
            iosAdguard.write("\n")

    hosts.write("\n")
    iosAdguard.write("\n")

    for line in hostnames.readlines():
        if (line[0] == "\n" or line[0] == "#"):
            continue
        hosts.write("0.0.0.0 " + line)
        iosAdguard.write(line)
        if (line[-1] != "\n"):
            hosts.write("\n")
            iosAdguard.write("\n")
